# Generated by Django 4.0.4 on 2022-05-20 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oh', '0002_city_add'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oh.city')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oh.country')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oh.district')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oh.state')),
            ],
        ),
        migrations.DeleteModel(
            name='City_add',
        ),
    ]
